services:
  python-opencv:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: python_env

    volumes:
      - ./script:/workspace/script
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      - DISPLAY=${DISPLAY}

    stdin_open: true
    tty: true

    network_mode: host